//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCECREAMPROJECT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_feedback
    {
        public int f_id { get; set; }

        [Display(Name="your Feed Back")]
        public string f_text { get; set; }

        [Display(Name="Email")]
        public string f_email { get; set; }

        [Display(Name="Name")]
        public string f_name { get; set; }

        [Display(Name="Contact")]
        public string f_contact { get; set; }
    }
}
